#######################################################################################
# Book settings
title: "Intermediate Data Programming"
author: "Hunter Schafer"
copyright: "2021"
logo: _static/logo.png

#######################################################################################
# Execution settings
execute:
  execute_notebooks: "off"

#######################################################################################
# Parse and render settings
parse:
  myst_enable_extensions:
    - amsmath
    - dollarmath

#######################################################################################
# HTML-specific settings
html:
  favicon: "_static/favicon.png"
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  # Kind of a hack, but I have to hardcode the GitHub URL to get this to work :(
  extra_navbar: '<a href="https://cse163.github.io/book/acknowledgements.html">Acknowledgements</a><br/>Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'
  extra_footer: 'Have feedback or spotted a bug? Please make a <a href="https://github.com/cse163/book/issues">GitHub issue</a> or contact <a href="https://homes.cs.washington.edu/~hschafer/">Hunter Schafer</a>!'

  comments:
    utterances:
      repo: "cse163/book"
      issue-term: "pathname"
      label: "💬 Comments"
      theme: "preferred-color-scheme"

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: https://mybinder.org
  colab_url: https://colab.research.google.com/

repository:
  url: https://github.com/cse163/book
  path_to_book: book_source/source/
  branch: main

#######################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions:
    - "sphinx_comments"
    - "sphinx_copybutton"
    - "sphinx_panels"
  local_extensions:
    "custom_directives": "ext/"
    "setup_templating": "ext/"
  config:
    suppress_warnings:
      - "myst.header"
